blueprint:
  name: MQTT - Hue smart button (press and hold) bedlampje
  description: Blueprint for press and hold actions for a Hue smart button.
  domain: automation
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Blueprints/main/mqtt_hue_smart_button_bedlampje.yaml
  input:
    smart_button:
      name: Smart button
      description: Hue smart button to use (pick the sensor that end with _action).
      selector:
        entity:
          integration: mqtt
          domain: sensor
    light_entity_bed:
      name: Night stand light
      selector:
        entity:
          domain: light
    light_entity_ceiling:
      name: Ceiling light
      selector:
        entity:
          domain: light

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input smart_button
  to:
    - 'on'
    - 'off'
    - 'hold'

action:
  - choose:
    # Button is being pressed.
    - conditions:
      - condition: template
        value_template: >
          {{ trigger.to_state.state in ['on', 'off'] }}
      sequence:
        - choose:
          - conditions:
              - condition: state
                entity_id: !input light_entity_bed
                state: 'off'
            sequence:
              - choose:
                - conditions:
                    - condition: template
                      value_template: > # Between 00:00 - 08:59
                        {{ now().hour < 9 }}
                  sequence:
                    - service: light.turn_on
                      data:
                        entity_id: !input light_entity_bed
                        profile: nachtlampje
                        transition: 1
                default:
                  - service: light.turn_on
                    data:
                      entity_id: !input light_entity_bed
                      profile: gedimd
                      transition: 1
          default:
            - service: light.turn_off
              entity_id: !input light_entity_bed

    # Button is being hold.
    - conditions:
      - condition: template
        value_template: >
          {{ trigger.to_state.state == 'hold' }}
      sequence:
        - choose:
          - conditions:
              - condition: state
                entity_id: !input light_entity_ceiling
                state: 'off'
            sequence:
              - choose:
                - conditions:
                    - condition: template
                      value_template: > # Between 00:00 - 08:59
                        {{ now().hour < 9 }}
                  sequence:
                    - service: light.turn_on
                      data:
                        entity_id: !input light_entity_ceiling
                        profile: nachtlampje
                        transition: 1
                default:
                  - service: light.turn_on
                    data:
                      entity_id: !input light_entity_ceiling
                      profile: gedimd
                      transition: 1
          default:
            - service: light.turn_off
              data:
                entity_id: !input light_entity_ceiling
                transition: 1
