blueprint:
  name: Zigbee2MQTT - Hue smart button - press and hold actions
  description: |
    This blueprint allows you to make automations based on the Hue smart button, connected to Zigbee2MQTT.
    Actions can be set up for single press and hold, hold you can configure with a cooldown, to prevent your actions from running on every single hold action.
  domain: automation
  source_url: https://raw.githubusercontent.com/golles/Home-Assistant-Blueprints/main/zigbee2mqtt_hue_smart_button_press_and_hold_actions.yaml
  input:
    smart_button:
      name: Smart button
      description: Hue smart button to use (pick the sensor that end with _action).
      selector:
        entity:
          integration: mqtt
          domain: sensor
    press_action:
      name: Press
      description: Action to run on button press.
      default: []
      selector:
        action:
    hold_action:
      name: Hold
      description: Action to run on button hold.
      default: []
      selector:
        action:
    hold_cooldown:
      name: Hold cool down
      description: Prevent this automation from being ran more often than only once while in this cool down.
      default: 3
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input smart_button
  to:
    - "on"
    - "off"
    - "hold"

action:
  - variables:
      to_state: "{{ trigger.to_state.state }}"

  - choose:
    # Button is being pressed.
    - conditions:
        - "{{ to_state in ['on', 'off'] }}"
      sequence: !input press_action

    # Button is being hold.
    - conditions:
        - "{{ to_state == 'hold' }}"
      sequence: 
        - choose:
          - conditions:
              - "{{ true }}"
            sequence: !input hold_action
        - delay:
           seconds: !input hold_cooldown
